name = "redde-bookmark"
compatibility_date = "2025-11-07"

# Static site configuration
pages_build_output_dir = "./dist"

# Optional: Add environment variables here or in Cloudflare dashboard
# [vars]
# PUBLIC_FB_API_KEY = ""
